### ISSUE TITLE
Keyboard input handler doesn't use GetKeyState

### ISSUE THREAD

**Issue by Rodrun** [Rodrun/rekwarfare-engine#1]
Currently, the keyboard input handler uses `key.keysym.sym` to get key pressed, but that can be problematic as it requires the function to be used within the event handling loop. It is generally much, much easier to handle keyboard input within an `Entity`'s `update` function.

**Comment by pastagatsan** [comment]
```
   💭 
```

🤔 

So you mean you don't want it to use `GetKeyState()` within the event loop, you'd rather pass SDL_event to your entity's `update()` ?

**Comment by Rodrun** [comment]
Actually, I was thinking of using `SDL_GetKeyboardState()` to get the key(s), I'll upload a commit for it sooner or later...
